Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2010"
  #config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.network "private_network", ip: "11.11.11.2"
  # config.vm.network "public_network"

  config.vm.synced_folder "./code", "/var/www/html"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "8384"

    vb.cpus = 4
  end
  
  config.vm.provision "shell", inline: <<-SHELL
     #!/bin/env/bash
     apt-get update
     apt-get full-upgrade -y


     apt install nginx -y
     apt install git -y

     apt install screen tmux \ 
         net-tools wireguard -y

     apt install npm nodejs -y
     apt install python3 pip3 -y

     apt install software-properties-common -y
     add-apt-repository ppa:ondrej/php
     apt update

     apt install php8.1-fpm php8.1-cli \ 
         php-redis php-mysqli -y

     apt install php-imagick  \ 
         php-json php-xml     \ 
         php-curl php-opcache \ 
         php-dev php-mbstring \ 
         composer -y

     apt install mysql-server mysql-client -y
  SHELL
end